"""
============================================================
SignSync

Runtime Animation Loader

Loads runtime animations generated by the
preprocessing pipeline.

Responsibilities

• Load runtime manifest
• Validate requested words
• Load animations
• Dequantize uint8 animations
• Cache animations in memory

Author:
SignSync
============================================================
"""

import json
import logging
from pathlib import Path
from typing import Dict
import numpy as np

from ml.config import paths


# ==========================================================
# Logger
# ==========================================================

logger = logging.getLogger(__name__)


# ==========================================================
# Runtime Cache
# ==========================================================

_animation_cache: Dict[str, np.ndarray] = {}

_manifest: Dict | None = None


# ==========================================================
# Manifest
# ==========================================================

def load_manifest() -> Dict:
    """
    Load runtime animation manifest.

    Manifest is cached after first load.
    """

    global _manifest

    if _manifest is not None:

        return _manifest

    manifest_file = paths.ANIMATION_MANIFEST

    if not manifest_file.exists():

        raise FileNotFoundError(

            "Runtime manifest not found.\n"

            "Run build_animation_database.py first."

        )

    logger.info(

        "Loading runtime manifest..."

    )

    with open(

        manifest_file,

        "r",

        encoding="utf-8"

    ) as file:

        _manifest = json.load(file)

    logger.info(

        "Loaded %d animations.",

        len(_manifest["words"])

    )

    return _manifest


# ==========================================================
# Runtime Validation
# ==========================================================

def animation_exists(
    word: str
) -> bool:
    """
    Check whether a runtime animation exists.
    """

    manifest = load_manifest()

    return word in manifest["words"]


# ==========================================================
# Animation Path
# ==========================================================

def get_animation_path(
    word: str
) -> Path:
    """
    Return runtime animation file path.
    """

    manifest = load_manifest()

    if word not in manifest["words"]:

        raise KeyError(

            f"No animation available for '{word}'."

        )

    filename = manifest["words"][word]["file"]

    return (

        paths.TEXT_TO_SIGN_ANIMATIONS /

        filename

    )


# ==========================================================
# Dequantization
# ==========================================================

def dequantize_animation(
    frames: np.ndarray,

    minimum: float,

    maximum: float

) -> np.ndarray:
    """
    Convert uint8 runtime animation
    back into float32.
    """

    scale = maximum - minimum

    if scale == 0:

        scale = 1.0

    animation = (

        frames.astype(np.float32)

        / 255.0

    ) * scale

    animation += minimum

    return animation
# ==========================================================
# Runtime Animation Loader
# ==========================================================

def load_animation(
    word: str
) -> np.ndarray:
    """
    Load a runtime animation.

    Uses RAM cache whenever possible.

    Parameters
    ----------
    word

    Returns
    -------
    float32 animation
    """

    word = word.lower().strip()

    if word in _animation_cache:

        logger.debug(
            "Cache hit: %s",
            word
        )

        return _animation_cache[word]

    animation_path = get_animation_path(
        word
    )

    logger.info(
        "Loading animation: %s",
        word
    )

    runtime = np.load(
        animation_path
    )

    animation = dequantize_animation(

        runtime["frames"],

        float(runtime["minimum"]),

        float(runtime["maximum"])

    )

    runtime.close()

    _animation_cache[word] = animation

    return animation


# ==========================================================
# Cache Utilities
# ==========================================================

def clear_cache() -> None:
    """
    Clear the runtime animation cache.
    """

    _animation_cache.clear()

    logger.info(
        "Runtime animation cache cleared."
    )


def cache_statistics() -> Dict:
    """
    Return cache statistics.
    """

    return {

        "cached_animations": len(
            _animation_cache
        ),

        "cached_words": sorted(
            _animation_cache.keys()
        )

    }


# ==========================================================
# Runtime Library Information
# ==========================================================

def runtime_statistics() -> Dict:
    """
    Return Runtime Animation Library statistics.
    """

    manifest = load_manifest()

    return {

        "schema_version":
            manifest["schema_version"],

        "runtime_version":
            manifest["runtime_version"],

        "compression":
            manifest["compression"],

        "animations":
            len(manifest["words"])

    }


# ==========================================================
# Standalone Test
# ==========================================================

if __name__ == "__main__":

    logging.basicConfig(

        level=logging.INFO,

        format="%(levelname)s | %(message)s"

    )

    stats = runtime_statistics()

    logger.info("")
    logger.info("=" * 60)
    logger.info("Runtime Animation Library")
    logger.info("=" * 60)

    logger.info(
        "Schema Version : %s",
        stats["schema_version"]
    )

    logger.info(
        "Runtime Version : %s",
        stats["runtime_version"]
    )

    logger.info(
        "Compression : %s",
        stats["compression"]
    )

    logger.info(
        "Animations : %d",
        stats["animations"]
    )

    logger.info("=" * 60)

    sample = "book"

    if animation_exists(sample):

        animation = load_animation(
            sample
        )

        logger.info("")

        logger.info(
            "Sample Animation : %s",
            sample
        )

        logger.info(
            "Shape : %s",
            animation.shape
        )

        logger.info(
            "Datatype : %s",
            animation.dtype
        )

        logger.info(
            "Cache : %s",
            cache_statistics()
        )

    else:

        logger.warning(
            "Sample animation '%s' not found.",
            sample
        )

# ==========================================================
# Runtime Manifest
# ==========================================================
    

def load_animation_sequence(
    words: list[str]
) -> dict[str, np.ndarray]:
    """
    Load multiple runtime animations.
    """

    animations = {}

    for word in words:

        animations[word] = load_animation(word)

    return animations